"$HOMEBREW_PREFIX"/bin/code-server --install-extension asvetliakov.vscode-neovim
"$HOMEBREW_PREFIX"/bin/code-server --install-extension ms-python.black-formatter
"$HOMEBREW_PREFIX"/bin/code-server --install-extension ms-python.python
"$HOMEBREW_PREFIX"/bin/code-server --install-extension ms-python.vscode-pylance
"$HOMEBREW_PREFIX"/bin/code-server --install-extension ms-toolsai.jupyter
"$HOMEBREW_PREFIX"/bin/code-server --install-extension ms-toolsai.jupyter-keymap
"$HOMEBREW_PREFIX"/bin/code-server --install-extension ms-toolsai.jupyter-renderers
"$HOMEBREW_PREFIX"/bin/code-server --install-extension ms-toolsai.vscode-jupyter-cell-tags
"$HOMEBREW_PREFIX"/bin/code-server --install-extension ms-toolsai.vscode-jupyter-slideshow
"$HOMEBREW_PREFIX"/bin/code-server --install-extension quarto.quarto
"$HOMEBREW_PREFIX"/bin/code-server --install-extension REditorSupport.r
"$HOMEBREW_PREFIX"/bin/code-server --install-extension TabNine.tabnine-vscode
"$HOMEBREW_PREFIX"/bin/code-server --install-extension ms-vsliveshare.vsliveshare
"$HOMEBREW_PREFIX"/bin/code-server --install-extension eamodio.gitlens
"$HOMEBREW_PREFIX"/bin/code-server --install-extension vscodevim.vim
"$HOMEBREW_PREFIX"/bin/code-server --disable-extension vscodevim.vim
"$HOMEBREW_PREFIX"/bin/code-server --install-extension jonsmithers.open-in-vim
