$HOMEBREW_PREFIX/bin/code --install-extension asvetliakov.vscode-neovim
$HOMEBREW_PREFIX/bin/code --install-extension ms-python.black-formatter
$HOMEBREW_PREFIX/bin/code --install-extension ms-python.python
$HOMEBREW_PREFIX/bin/code --install-extension ms-python.vscode-pylance
$HOMEBREW_PREFIX/bin/code --install-extension ms-toolsai.jupyter
$HOMEBREW_PREFIX/bin/code --install-extension ms-toolsai.jupyter-keymap
$HOMEBREW_PREFIX/bin/code --install-extension ms-toolsai.jupyter-renderers
$HOMEBREW_PREFIX/bin/code --install-extension ms-toolsai.vscode-jupyter-cell-tags
$HOMEBREW_PREFIX/bin/code --install-extension ms-toolsai.vscode-jupyter-slideshow
$HOMEBREW_PREFIX/bin/code --install-extension quarto.quarto
$HOMEBREW_PREFIX/bin/code --install-extension REditorSupport.r
$HOMEBREW_PREFIX/bin/code --install-extension TabNine.tabnine-vscode
$HOMEBREW_PREFIX/bin/code --install-extension ms-vsliveshare.vsliveshare
