$HOMEBREW_PREFIX/bin/codium --install-extension asvetliakov.vscode-neovim
$HOMEBREW_PREFIX/bin/codium --install-extension ms-python.python
$HOMEBREW_PREFIX/bin/codium --install-extension ms-toolsai.jupyter
$HOMEBREW_PREFIX/bin/codium --install-extension ms-toolsai.jupyter-keymap
$HOMEBREW_PREFIX/bin/codium --install-extension ms-toolsai.jupyter-renderers
$HOMEBREW_PREFIX/bin/codium --install-extension ms-toolsai.vscode-jupyter-cell-tags
$HOMEBREW_PREFIX/bin/codium --install-extension ms-toolsai.vscode-jupyter-slideshow
$HOMEBREW_PREFIX/bin/codium --install-extension quarto.quarto
$HOMEBREW_PREFIX/bin/codium --install-extension REditorSupport.r
$HOMEBREW_PREFIX/bin/codium --install-extension TabNine.tabnine-vscode
